//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vital.Business.Repositories.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vital.Business.Repositories.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @pathName NVARCHAR(Max)
        ///DECLARE @dateInfo NVARCHAR(Max)
        ///DECLARE @databaseName NVARCHAR(512) 
        ///SET @databaseName = &apos;VitalExpert&apos; 
        ///SET @dateInfo = Convert(varchar(8), GETDATE(), 112) + &apos;_&apos; + Replace((Convert(varchar(8), GETDATE(), 108)),&apos;:&apos;,&apos;-&apos;)
        ///SET @pathName = &apos;@PATH\Vital_Expert_Backup_&apos; + @dateInfo + &apos;.bak&apos; 
        ///BACKUP DATABASE @databaseName TO DISK = @pathName WITH NOFORMAT, NOINIT, NAME = N&apos;VitalExpert&apos;, SKIP, NOREWIND, NOUNLOAD,  STATS = 10
        ///GO.
        /// </summary>
        public static string DBBackup {
            get {
                return ResourceManager.GetString("DBBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///Deployment script for VitalExpert
        ///*/
        ///
        ///GO
        ///SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;
        ///
        ///SET NUMERIC_ROUNDABORT OFF;
        ///
        ///
        ///GO
        ///:setvar DatabaseName &quot;VitalExpert&quot;
        ///:setvar DefaultDataPath &quot;{0}&quot;
        ///:setvar DefaultLogPath &quot;{0}&quot;
        ///
        ///GO
        ///USE [master]
        ///
        ///GO
        ///:on error exit
        ///GO
        ///IF (DB_ID(N&apos;$(DatabaseName)&apos;) IS NOT NULL
        ///    AND DATABASEPROPERTYEX(N&apos;$(DatabaseName)&apos;,&apos;Status&apos;) &lt;&gt; N&apos;ONLINE&apos;)
        ///BEGIN
        ///    RAISERROR(N&apos;The state of the target database, %s, i [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DBCreate {
            get {
                return ResourceManager.GetString("DBCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE MASTER
        ///
        ///ALTER DATABASE VitalExpertTemp SET SINGLE_USER WITH ROLLBACK IMMEDIATE 
        ///
        ///GO
        ///
        ///DROP DATABASE VitalExpertTemp
        ///
        ///GO.
        /// </summary>
        public static string DBDrop {
            get {
                return ResourceManager.GetString("DBDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE MASTER
        ///
        ///ALTER DATABASE VitalExpert SET SINGLE_USER WITH ROLLBACK IMMEDIATE 
        ///
        ///GO
        ///
        ///RESTORE DATABASE VitalExpert 
        ///FROM DISK = N&apos;@PATH&apos; 
        ///WITH MOVE &apos;VitalExpert&apos; TO &apos;@DATAPATH@VitalExpert.mdf&apos;, 
        ///	 MOVE &apos;VitalExpert_log&apos; TO &apos;@DATAPATH@VitalExpert.ldf&apos;, 
        ///	 NOUNLOAD, 
        ///	 REPLACE
        ///GO
        ///
        ///ALTER DATABASE VitalExpert SET MULTI_USER
        ///
        ///GO.
        /// </summary>
        public static string DBRestore {
            get {
                return ResourceManager.GetString("DBRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DBUpdate {
            get {
                return ResourceManager.GetString("DBUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE MASTER
        ///GO
        ///
        ///RESTORE DATABASE VitalExpertTemp
        ///FROM DISK = N&apos;@PATH&apos; 
        ///WITH MOVE &apos;VitalExpertTemp&apos; TO &apos;@DATAPATH@VitalExpertTemp.mdf&apos;, 
        ///	 MOVE &apos;VitalExpertTemp_log&apos; TO &apos;@DATAPATH@VitalExpertTemp.ldf&apos;, 
        ///	 NOUNLOAD, 
        ///	 REPLACE
        ///GO.
        /// </summary>
        public static string DBVerify {
            get {
                return ResourceManager.GetString("DBVerify", resourceCulture);
            }
        }
    }
}
